; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppId={{A7D3F5E1-7B8C-4F21-9D64-DANZFLYOUT1000}
AppName=DanzFlyout
AppVersion=1.0.1
AppPublisher=DanzFlyout

DefaultDirName={localappdata}\DanzFlyout
DefaultGroupName=DanzFlyout
DisableProgramGroupPage=yes

OutputDir=.
OutputBaseFilename=DanzFlyout_Setup_1.0.1

Compression=lzma
SolidCompression=yes
WizardStyle=modern

ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=lowest

UninstallDisplayIcon={app}\DanzFlyout.exe
SetupIconFile=F:\DanzFlyout\Assets\DanzFlyout.ico


[Files]
Source: "F:\DanzFlyout\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs


[Icons]
Name: "{group}\DanzFlyout"; Filename: "{app}\DanzFlyout.exe"
Name: "{autodesktop}\DanzFlyout"; Filename: "{app}\DanzFlyout.exe"


[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "DanzFlyout"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run"; ValueType: binary; ValueName: "DanzFlyout"; Flags: uninsdeletevalue


[UninstallRun]
Filename: "{cmd}"; Parameters: "/C taskkill /F /IM DanzFlyout.exe"; Flags: runhidden waituntilterminated; RunOnceId: "TerminateDanzFlyout"


[UninstallDelete]
Type: filesandordirs; Name: "{app}"